name: survival
channels:
  - conda-forge
dependencies:
  - r-essentials
  - r-base=3
  - jupyterlab
  - r-survival
  - r-dplyr
  - r-ggplot2
  - r-haven
  - r-flexsurv
  - r-survminer
  - r-stargazer
  - r-eha
